In [54]:
#Comprehension is combination of mapping and filter
#first if else condn defines mapping and 2nd if condn defines filter
#first filtering is done and then mapping is done

In [1]:
a=[1,3,5,7,9]
b=[i**2 for i in a]

In [2]:
b

[1, 9, 25, 49, 81]

In [10]:
c=[i for i in range(10) if i%2==0]

In [11]:
c

[0, 2, 4, 6, 8]

In [12]:
d=[i**2 for i in range(10) if i%2==0]

In [13]:
d

[0, 4, 16, 36, 64]

In [41]:
e=[i for i in range(50) if i%5==0]
f=[i**2 for i in e if i%2==0]

In [42]:
e

[0, 5, 10, 15, 20, 25, 30, 35, 40, 45]

In [43]:
f

[0, 100, 400, 900, 1600]

In [45]:
g=[i**2 if i%2==0 else i**3 i for i in range(50) if i%5==0]

SyntaxError: invalid syntax (<ipython-input-45-7c4678c85919>, line 1)

In [46]:
g=[i**2 if i%2==0 else i**3 for i in range(10)]

In [47]:
g

[0, 1, 4, 27, 16, 125, 36, 343, 64, 729]

In [52]:
h=[i**2 if i%2==0 else None for i in range(50) if i%5==0]#to print square of even numbers divisible by 5 with comprehension

In [53]:
h

[0, None, 100, None, 400, None, 900, None, 1600, None]

In [56]:
x=[i for i in range(1,10)]#1
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [60]:
x=[i for i in range(21) if i%2==0]#2
print(x)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [101]:
x=[i for i in "MATHEMATICS" if i in "AEIOU"]#3
print(x)

['A', 'E', 'A', 'I']

In [66]:
x=[i for i in range(1000) if i%7==0]#4
print(x)

[0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126, 133, 140, 147, 154, 161, 168, 175, 182, 189, 196, 203, 210, 217, 224, 231, 238, 245, 252, 259, 266, 273, 280, 287, 294, 301, 308, 315, 322, 329, 336, 343, 350, 357, 364, 371, 378, 385, 392, 399, 406, 413, 420, 427, 434, 441, 448, 455, 462, 469, 476, 483, 490, 497, 504, 511, 518, 525, 532, 539, 546, 553, 560, 567, 574, 581, 588, 595, 602, 609, 616, 623, 630, 637, 644, 651, 658, 665, 672, 679, 686, 693, 700, 707, 714, 721, 728, 735, 742, 749, 756, 763, 770, 777, 784, 791, 798, 805, 812, 819, 826, 833, 840, 847, 854, 861, 868, 875, 882, 889, 896, 903, 910, 917, 924, 931, 938, 945, 952, 959, 966, 973, 980, 987, 994]

In [47]:
a=3
x=[i for i in range(1000) if "3" in str(i)]#5
print(x)

[3, 13, 23, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 43, 53, 63, 73, 83, 93, 103, 113, 123, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 143, 153, 163, 173, 183, 193, 203, 213, 223, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 243, 253, 263, 273, 283, 293, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 403, 413, 423, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 443, 453, 463, 473, 483, 493, 503, 513, 523, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 543, 553, 563, 573, 583, 593, 603, 613, 623, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 643, 653, 663, 673, 683, 693, 703, 713, 723, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 743, 753, 763, 773, 783, 793, 803, 813, 823, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 843, 853, 863, 873, 883, 893, 903, 913, 923, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 943, 953, 963, 973, 983, 993]

In [45]:
x=[i for i in "Nischal S h restha" if i in " "]#6
len(x)

3

In [13]:
#7
x=[i for i in "MATHEMATICS" if i not in "AEIOU"]
print(x)

['M', 'T', 'H', 'M', 'T', 'C', 'S']

In [21]:
#8
a="i am cortana. i am in windows"
x=[i for i in a.split( ) if len(i)<4]
print(x)

['i', 'am', 'i', 'am', 'in']

1. Use a dictionary comprehension to count the length of each word in a sentence.

2. Use a nested list comprehension to find all of the numbers from 1-1000 that are divisible by any single digit besides 1 (2-9)

3. For all the numbers 1-1000, use a nested list/dictionary comprehension to find the highest single digit any of the numbers is divisible by

Dictionary Comprehension

1. Use a dictionary comprehension to count the length of each word in a sentence.

In [90]:
d="THis is Python this"
{word:len(word) for word in d.split()}

{'THis': 4, 'is': 2, 'Python': 6, 'this': 4}

2. Use a nested list comprehension to find all of the numbers from 1-1000 that are divisible by any single digit besides 1 (2-9)

In [81]:
x={j for i in range(2,10) for j in range(1000) if j%i==0}
print(list(set(x)))

[0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24, 25, 26, 27, 28, 30, 32, 33, 34, 35, 36, 38, 39, 40, 42, 44, 45, 46, 48, 49, 50, 51, 52, 54, 55, 56, 57, 58, 60, 62, 63, 64, 65, 66, 68, 69, 70, 72, 74, 75, 76, 77, 78, 80, 81, 82, 84, 85, 86, 87, 88, 90, 91, 92, 93, 94, 95, 96, 98, 99, 100, 102, 104, 105, 106, 108, 110, 111, 112, 114, 115, 116, 117, 118, 119, 120, 122, 123, 124, 125, 126, 128, 129, 130, 132, 133, 134, 135, 136, 138, 140, 141, 142, 144, 145, 146, 147, 148, 150, 152, 153, 154, 155, 156, 158, 159, 160, 161, 162, 164, 165, 166, 168, 170, 171, 172, 174, 175, 176, 177, 178, 180, 182, 183, 184, 185, 186, 188, 189, 190, 192, 194, 195, 196, 198, 200, 201, 202, 203, 204, 205, 206, 207, 208, 210, 212, 213, 214, 215, 216, 217, 218, 219, 220, 222, 224, 225, 226, 228, 230, 231, 232, 234, 235, 236, 237, 238, 240, 242, 243, 244, 245, 246, 248, 249, 250, 252, 254, 255, 256, 258, 259, 260, 261, 262, 264, 265, 266, 267, 268, 270, 272, 273, 274, 275, 276, 278, 279, 280, 282, 284, 285, 286, 287, 288, 290, 291, 292, 294, 295, 296, 297, 298, 300, 301, 302, 303, 304, 305, 306, 308, 309, 310, 312, 314, 315, 316, 318, 320, 321, 322, 324, 325, 326, 327, 328, 329, 330, 332, 333, 334, 335, 336, 338, 339, 340, 342, 343, 344, 345, 346, 348, 350, 351, 352, 354, 355, 356, 357, 358, 360, 362, 363, 364, 365, 366, 368, 369, 370, 371, 372, 374, 375, 376, 378, 380, 381, 382, 384, 385, 386, 387, 388, 390, 392, 393, 394, 395, 396, 398, 399, 400, 402, 404, 405, 406, 408, 410, 411, 412, 413, 414, 415, 416, 417, 418, 420, 422, 423, 424, 425, 426, 427, 428, 429, 430, 432, 434, 435, 436, 438, 440, 441, 442, 444, 445, 446, 447, 448, 450, 452, 453, 454, 455, 456, 458, 459, 460, 462, 464, 465, 466, 468, 469, 470, 471, 472, 474, 475, 476, 477, 478, 480, 482, 483, 484, 485, 486, 488, 489, 490, 492, 494, 495, 496, 497, 498, 500, 501, 502, 504, 505, 506, 507, 508, 510, 511, 512, 513, 514, 515, 516, 518, 519, 520, 522, 524, 525, 526, 528, 530, 531, 532, 534, 535, 536, 537, 538, 539, 540, 542, 543, 544, 545, 546, 548, 549, 550, 552, 553, 554, 555, 556, 558, 560, 561, 562, 564, 565, 566, 567, 568, 570, 572, 573, 574, 575, 576, 578, 579, 580, 581, 582, 584, 585, 586, 588, 590, 591, 592, 594, 595, 596, 597, 598, 600, 602, 603, 604, 605, 606, 608, 609, 610, 612, 614, 615, 616, 618, 620, 621, 622, 623, 624, 625, 626, 627, 628, 630, 632, 633, 634, 635, 636, 637, 638, 639, 640, 642, 644, 645, 646, 648, 650, 651, 652, 654, 655, 656, 657, 658, 660, 662, 663, 664, 665, 666, 668, 669, 670, 672, 674, 675, 676, 678, 679, 680, 681, 682, 684, 685, 686, 687, 688, 690, 692, 693, 694, 695, 696, 698, 699, 700, 702, 704, 705, 706, 707, 708, 710, 711, 712, 714, 715, 716, 717, 718, 720, 721, 722, 723, 724, 725, 726, 728, 729, 730, 732, 734, 735, 736, 738, 740, 741, 742, 744, 745, 746, 747, 748, 749, 750, 752, 753, 754, 755, 756, 758, 759, 760, 762, 763, 764, 765, 766, 768, 770, 771, 772, 774, 775, 776, 777, 778, 780, 782, 783, 784, 785, 786, 788, 789, 790, 791, 792, 794, 795, 796, 798, 800, 801, 802, 804, 805, 806, 807, 808, 810, 812, 813, 814, 815, 816, 818, 819, 820, 822, 824, 825, 826, 828, 830, 831, 832, 833, 834, 835, 836, 837, 838, 840, 842, 843, 844, 845, 846, 847, 848, 849, 850, 852, 854, 855, 856, 858, 860, 861, 862, 864, 865, 866, 867, 868, 870, 872, 873, 874, 875, 876, 878, 879, 880, 882, 884, 885, 886, 888, 889, 890, 891, 892, 894, 895, 896, 897, 898, 900, 902, 903, 904, 905, 906, 908, 909, 910, 912, 914, 915, 916, 917, 918, 920, 921, 922, 924, 925, 926, 927, 928, 930, 931, 932, 933, 934, 935, 936, 938, 939, 940, 942, 944, 945, 946, 948, 950, 951, 952, 954, 955, 956, 957, 958, 959, 960, 962, 963, 964, 965, 966, 968, 969, 970, 972, 973, 974, 975, 976, 978, 980, 981, 982, 984, 985, 986, 987, 988, 990, 992, 993, 994, 995, 996, 998, 999]

3. For all the numbers 1-1000, use a nested list/dictionary comprehension to find the highest single digit any of the numbers is divisible by

In [80]:
x={k:v for v in range(2,10) for k in range(1,1000) if k%v==0}
print(x)

{2: 2, 4: 4, 6: 6, 8: 8, 10: 5, 12: 6, 14: 7, 16: 8, 18: 9, 20: 5, 22: 2, 24: 8, 26: 2, 28: 7, 30: 6, 32: 8, 34: 2, 36: 9, 38: 2, 40: 8, 42: 7, 44: 4, 46: 2, 48: 8, 50: 5, 52: 4, 54: 9, 56: 8, 58: 2, 60: 6, 62: 2, 64: 8, 66: 6, 68: 4, 70: 7, 72: 9, 74: 2, 76: 4, 78: 6, 80: 8, 82: 2, 84: 7, 86: 2, 88: 8, 90: 9, 92: 4, 94: 2, 96: 8, 98: 7, 100: 5, 102: 6, 104: 8, 106: 2, 108: 9, 110: 5, 112: 8, 114: 6, 116: 4, 118: 2, 120: 8, 122: 2, 124: 4, 126: 9, 128: 8, 130: 5, 132: 6, 134: 2, 136: 8, 138: 6, 140: 7, 142: 2, 144: 9, 146: 2, 148: 4, 150: 6, 152: 8, 154: 7, 156: 6, 158: 2, 160: 8, 162: 9, 164: 4, 166: 2, 168: 8, 170: 5, 172: 4, 174: 6, 176: 8, 178: 2, 180: 9, 182: 7, 184: 8, 186: 6, 188: 4, 190: 5, 192: 8, 194: 2, 196: 7, 198: 9, 200: 8, 202: 2, 204: 6, 206: 2, 208: 8, 210: 7, 212: 4, 214: 2, 216: 9, 218: 2, 220: 5, 222: 6, 224: 8, 226: 2, 228: 6, 230: 5, 232: 8, 234: 9, 236: 4, 238: 7, 240: 8, 242: 2, 244: 4, 246: 6, 248: 8, 250: 5, 252: 9, 254: 2, 256: 8, 258: 6, 260: 5, 262: 2, 264: 8, 266: 7, 268: 4, 270: 9, 272: 8, 274: 2, 276: 6, 278: 2, 280: 8, 282: 6, 284: 4, 286: 2, 288: 9, 290: 5, 292: 4, 294: 7, 296: 8, 298: 2, 300: 6, 302: 2, 304: 8, 306: 9, 308: 7, 310: 5, 312: 8, 314: 2, 316: 4, 318: 6, 320: 8, 322: 7, 324: 9, 326: 2, 328: 8, 330: 6, 332: 4, 334: 2, 336: 8, 338: 2, 340: 5, 342: 9, 344: 8, 346: 2, 348: 6, 350: 7, 352: 8, 354: 6, 356: 4, 358: 2, 360: 9, 362: 2, 364: 7, 366: 6, 368: 8, 370: 5, 372: 6, 374: 2, 376: 8, 378: 9, 380: 5, 382: 2, 384: 8, 386: 2, 388: 4, 390: 6, 392: 8, 394: 2, 396: 9, 398: 2, 400: 8, 402: 6, 404: 4, 406: 7, 408: 8, 410: 5, 412: 4, 414: 9, 416: 8, 418: 2, 420: 7, 422: 2, 424: 8, 426: 6, 428: 4, 430: 5, 432: 9, 434: 7, 436: 4, 438: 6, 440: 8, 442: 2, 444: 6, 446: 2, 448: 8, 450: 9, 452: 4, 454: 2, 456: 8, 458: 2, 460: 5, 462: 7, 464: 8, 466: 2, 468: 9, 470: 5, 472: 8, 474: 6, 476: 7, 478: 2, 480: 8, 482: 2, 484: 4, 486: 9, 488: 8, 490: 7, 492: 6, 494: 2, 496: 8, 498: 6, 500: 5, 502: 2, 504: 9, 506: 2, 508: 4, 510: 6, 512: 8, 514: 2, 516: 6, 518: 7, 520: 8, 522: 9, 524: 4, 526: 2, 528: 8, 530: 5, 532: 7, 534: 6, 536: 8, 538: 2, 540: 9, 542: 2, 544: 8, 546: 7, 548: 4, 550: 5, 552: 8, 554: 2, 556: 4, 558: 9, 560: 8, 562: 2, 564: 6, 566: 2, 568: 8, 570: 6, 572: 4, 574: 7, 576: 9, 578: 2, 580: 5, 582: 6, 584: 8, 586: 2, 588: 7, 590: 5, 592: 8, 594: 9, 596: 4, 598: 2, 600: 8, 602: 7, 604: 4, 606: 6, 608: 8, 610: 5, 612: 9, 614: 2, 616: 8, 618: 6, 620: 5, 622: 2, 624: 8, 626: 2, 628: 4, 630: 9, 632: 8, 634: 2, 636: 6, 638: 2, 640: 8, 642: 6, 644: 7, 646: 2, 648: 9, 650: 5, 652: 4, 654: 6, 656: 8, 658: 7, 660: 6, 662: 2, 664: 8, 666: 9, 668: 4, 670: 5, 672: 8, 674: 2, 676: 4, 678: 6, 680: 8, 682: 2, 684: 9, 686: 7, 688: 8, 690: 6, 692: 4, 694: 2, 696: 8, 698: 2, 700: 7, 702: 9, 704: 8, 706: 2, 708: 6, 710: 5, 712: 8, 714: 7, 716: 4, 718: 2, 720: 9, 722: 2, 724: 4, 726: 6, 728: 8, 730: 5, 732: 6, 734: 2, 736: 8, 738: 9, 740: 5, 742: 7, 744: 8, 746: 2, 748: 4, 750: 6, 752: 8, 754: 2, 756: 9, 758: 2, 760: 8, 762: 6, 764: 4, 766: 2, 768: 8, 770: 7, 772: 4, 774: 9, 776: 8, 778: 2, 780: 6, 782: 2, 784: 8, 786: 6, 788: 4, 790: 5, 792: 9, 794: 2, 796: 4, 798: 7, 800: 8, 802: 2, 804: 6, 806: 2, 808: 8, 810: 9, 812: 7, 814: 2, 816: 8, 818: 2, 820: 5, 822: 6, 824: 8, 826: 7, 828: 9, 830: 5, 832: 8, 834: 6, 836: 4, 838: 2, 840: 8, 842: 2, 844: 4, 846: 9, 848: 8, 850: 5, 852: 6, 854: 7, 856: 8, 858: 6, 860: 5, 862: 2, 864: 9, 866: 2, 868: 7, 870: 6, 872: 8, 874: 2, 876: 6, 878: 2, 880: 8, 882: 9, 884: 4, 886: 2, 888: 8, 890: 5, 892: 4, 894: 6, 896: 8, 898: 2, 900: 9, 902: 2, 904: 8, 906: 6, 908: 4, 910: 7, 912: 8, 914: 2, 916: 4, 918: 9, 920: 8, 922: 2, 924: 7, 926: 2, 928: 8, 930: 6, 932: 4, 934: 2, 936: 9, 938: 7, 940: 5, 942: 6, 944: 8, 946: 2, 948: 6, 950: 5, 952: 8, 954: 9, 956: 4, 958: 2, 960: 8, 962: 2, 964: 4, 966: 7, 968: 8, 970: 5, 972: 9, 974: 2, 976: 8, 978: 6, 980: 7, 982: 2, 984: 8, 986: 2, 988: 4, 990: 9, 992: 8, 994: 7, 996: 6, 998: 2, 3: 3, 9: 9, 15: 5, 21: 7, 27: 9, 33: 3, 39: 3, 45: 9, 51: 3, 57: 3, 63: 9, 69: 3, 75: 5, 81: 9, 87: 3, 93: 3, 99: 9, 105: 7, 111: 3, 117: 9, 123: 3, 129: 3, 135: 9, 141: 3, 147: 7, 153: 9, 159: 3, 165: 5, 171: 9, 177: 3, 183: 3, 189: 9, 195: 5, 201: 3, 207: 9, 213: 3, 219: 3, 225: 9, 231: 7, 237: 3, 243: 9, 249: 3, 255: 5, 261: 9, 267: 3, 273: 7, 279: 9, 285: 5, 291: 3, 297: 9, 303: 3, 309: 3, 315: 9, 321: 3, 327: 3, 333: 9, 339: 3, 345: 5, 351: 9, 357: 7, 363: 3, 369: 9, 375: 5, 381: 3, 387: 9, 393: 3, 399: 7, 405: 9, 411: 3, 417: 3, 423: 9, 429: 3, 435: 5, 441: 9, 447: 3, 453: 3, 459: 9, 465: 5, 471: 3, 477: 9, 483: 7, 489: 3, 495: 9, 501: 3, 507: 3, 513: 9, 519: 3, 525: 7, 531: 9, 537: 3, 543: 3, 549: 9, 555: 5, 561: 3, 567: 9, 573: 3, 579: 3, 585: 9, 591: 3, 597: 3, 603: 9, 609: 7, 615: 5, 621: 9, 627: 3, 633: 3, 639: 9, 645: 5, 651: 7, 657: 9, 663: 3, 669: 3, 675: 9, 681: 3, 687: 3, 693: 9, 699: 3, 705: 5, 711: 9, 717: 3, 723: 3, 729: 9, 735: 7, 741: 3, 747: 9, 753: 3, 759: 3, 765: 9, 771: 3, 777: 7, 783: 9, 789: 3, 795: 5, 801: 9, 807: 3, 813: 3, 819: 9, 825: 5, 831: 3, 837: 9, 843: 3, 849: 3, 855: 9, 861: 7, 867: 3, 873: 9, 879: 3, 885: 5, 891: 9, 897: 3, 903: 7, 909: 9, 915: 5, 921: 3, 927: 9, 933: 3, 939: 3, 945: 9, 951: 3, 957: 3, 963: 9, 969: 3, 975: 5, 981: 9, 987: 7, 993: 3, 999: 9, 5: 5, 25: 5, 35: 7, 55: 5, 65: 5, 85: 5, 95: 5, 115: 5, 125: 5, 145: 5, 155: 5, 175: 7, 185: 5, 205: 5, 215: 5, 235: 5, 245: 7, 265: 5, 275: 5, 295: 5, 305: 5, 325: 5, 335: 5, 355: 5, 365: 5, 385: 7, 395: 5, 415: 5, 425: 5, 445: 5, 455: 7, 475: 5, 485: 5, 505: 5, 515: 5, 535: 5, 545: 5, 565: 5, 575: 5, 595: 7, 605: 5, 625: 5, 635: 5, 655: 5, 665: 7, 685: 5, 695: 5, 715: 5, 725: 5, 745: 5, 755: 5, 775: 5, 785: 5, 805: 7, 815: 5, 835: 5, 845: 5, 865: 5, 875: 7, 895: 5, 905: 5, 925: 5, 935: 5, 955: 5, 965: 5, 985: 5, 995: 5, 7: 7, 49: 7, 77: 7, 91: 7, 119: 7, 133: 7, 161: 7, 203: 7, 217: 7, 259: 7, 287: 7, 301: 7, 329: 7, 343: 7, 371: 7, 413: 7, 427: 7, 469: 7, 497: 7, 511: 7, 539: 7, 553: 7, 581: 7, 623: 7, 637: 7, 679: 7, 707: 7, 721: 7, 749: 7, 763: 7, 791: 7, 833: 7, 847: 7, 889: 7, 917: 7, 931: 7, 959: 7, 973: 7}

BIG CHALLANGE